name = "SymbolicCodegen"
uuid = "fc9b0551-4f1b-42e1-8440-e8a535f5a551"
authors = ["Chad Scherrer <chad.scherrer@gmail.com> and contributors"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"

[compat]
DataStructures = "0.18"
MacroTools = "0.5"
SymbolicUtils = "0.7"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
